apiVersion: v1
kind: Service
metadata:
  name: {{ include "gamemac.fullname" . }}
  labels:
    {{- include "gamemac.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-backend-label: "gamehub/role-alb=true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "gamemac.selectorLabels" . | nindent 4 }}

